#!/usr/bin/perl -n

use POSIX qw(strftime);

BEGIN{
	$date= strftime("%a, %d %b %Y %H:%M:%S +0000", gmtime(time()));
	my $cmd= '{print $3}';
	$timeout= `awk '$cmd' timeout.h`;
	chomp $timeout;
}

chomp;
s/"//g;

($cc,$rn,$rc)= split ',';

$len=length qq/{"s":{"sc":"OK"},"d":{"cc":"$cc","rc":"$rc","rn":"$rn"}}\n/;

print <<___;
{str("HTTP/1.1 200 OK\\n\\
Content-Type: application/json;charset=utf-8\\n\\
Date: $date\\n\\
Content-Length: $len\\n\\
\\n\\
{\\"s\\":{\\"sc\\":\\"OK\\"},\\"d\\":{\\"cc\\":\\"$cc\\",\\"rc\\":\\"$rc\\",\\"rn\\":\\"$rn\\"}}\\n"),
str("HTTP/1.1 200 OK\\n\\
Content-Type: application/json;charset=utf-8\\n\\
Date: $date\\n\\
Content-Length: $len\\n\\
Keep-Alive: timeout=$timeout\\n\\
Connection: Keep-Alive\\n\\
\\n\\
{\\"s\\":{\\"sc\\":\\"OK\\"},\\"d\\":{\\"cc\\":\\"$cc\\",\\"rc\\":\\"$rc\\",\\"rn\\":\\"$rn\\"}}\\n")},
___
