#!/bin/sh
set -vex

set $(git ls-tree -r master --name-only | fgrep -v git | sed 's}/.*}}') ip.map.{gz,bz2} 

echo "$@"

. ~/.ssh-agent.sh
scp -vri "./$@" ubuntu@54.204.234.199:src/. &

for f in "$@"; do
	aws s3 cp "./$f" s3://databus-dev/geo/$f;
done &

git push
wait

for f in "$@"; do
	echo ">>$f<<"
done
